spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sample
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
  web:
    resources:
      add-mappings: true
ext:
  cookie:
    secure: off
    same-site: lax
  web:
    log:
      enabled: true
      request: true
      trace: true
  redis:
    redis-serializer: fastjson
  auth:
    user-key: id
  mybatis:
    log: true
mybatis-flex:
  global-config:
    deleted-value-of-logic-delete: NOW()
    normal-value-of-logic-delete: null